services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME_DIR}:${HOME_DIR}
      - dockhand_data:/app/data

volumes:
  dockhand_data:
    name: dockhand_data

networks:
  default:
    name: dockhand_network